### ISSUE TITLE
Error: Cannot find module 'sass'

### ISSUE THREAD

**Issue by dragonwt** [Cuberto/svg-distortion-effect-demo#1]
gulp-sass don't have default sass-compiler.please install sass.
in gulpfile.js add this
const gulp = require('gulp');
const sass = require('gulp-sass')(require('sass'));
and change to this
        .pipe(sass({
            "includePaths": "node_modules"
        }))

**Comment by Drafteed** [comment]
Should be fixed in 117d2bb
